# Generated by Django 4.1.7 on 2023-04-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_newuser_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.confirmationcode'),
        ),
    ]
