# Generated by Django 4.1.7 on 2023-04-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
