# Generated by Django 4.1.7 on 2023-04-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_newuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='code',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='name',
        ),
        migrations.AddField(
            model_name='newuser',
            name='codes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.confirmationcode'),
        ),
    ]
