# Generated by Django 4.1.7 on 2023-04-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_newuser_code_remove_newuser_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='codes',
            new_name='code',
        ),
    ]
