# Generated by Django 4.1.7 on 2023-04-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_codes_newuser_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
